defaults: &defaults
  sessions:
    default:
      database: babyio
      hosts:
        - localhost:27017
      options:
        consistency: :strong

development:
  <<: *defaults

test:
  sessions:
    default:
      database: babyio
      hosts:
        - localhost:27017
      options:
        consistency: :strong

<% if ENV['MONGOLAB_URI'] %>
  <% uri = URI.parse(ENV['MONGOLAB_URI']) %>
production:
  <<: *defaults
  sessions:
    default:
      <<: *default_session
      database: <%= uri.path.sub('/','') %>
      username: <%= uri.user %>
      password: <%= uri.password %>
      hosts:
        - <%= uri.host %>:<%= uri.port %>
<% end %>
